In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Electric_Vehicle_Population_Data.csv to Electric_Vehicle_Population_Data.csv

In [4]:
df = pd.read_csv('Electric_Vehicle_Population_Data.csv')
df.sort_values(by='State')

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
39874,3FA6P0PU2G,Fairbanks North Star,Fairbanks,AK,99701.0,2016,FORD,FUSION,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19,0,NaN,478396124,POINT (-147.72213 64.84527),NaN,2.090001e+09
106396,5YJ3E1EBXK,Lee,Smiths Station,AL,36877.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220,0,NaN,225833863,POINT (-85.08963 32.54086),NaN,1.081042e+09
1800,1N4BZ1CPXK,Pulaski,Little Rock,AR,72207.0,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150,0,NaN,219350309,POINT (-92.33405 34.77306),NaN,5.119002e+09
16217,5YJ3E1EB9L,Pulaski,Little Rock,AR,72207.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,322,0,NaN,223647805,POINT (-92.33405 34.77306),NaN,5.119002e+09
101721,7SAYGDEF1N,Pulaski,Little Rock,AR,72205.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,NaN,209624852,POINT (-92.32538 34.75693),NaN,5.119002e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41622,5YJXCBE29H,Pierce,Lakewood,WA,98499.0,2017,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,200,0,28.0,243798733,POINT (-122.51495 47.16195),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,5.305307e+10
41634,7SAYGDEE3N,King,Renton,WA,98056.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,41.0,196569775,POINT (-122.18463 47.49929),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
102682,5YJYGAEE4M,Douglas,South Range,WI,54874.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,NaN,167228722,POINT (-91.98379 46.60774),NaN,5.503103e+10
107658,WB523CF01N,Sheridan,Sheridan,WY,82801.0,2022,BMW,IX,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,NaN,205813730,POINT (-106.95587 44.79792),NaN,5.603300e+10
124382,5YJ3E1EB2L,Laramie,Cheyenne,WY,82001.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,322,0,NaN,133911886,POINT (-104.82154 41.13481),NaN,5.602100e+10

In [10]:
df.groupby('State').agg({'Electric Range': 'mean'}).sort_values('Electric Range', ascending=False).head()

       Electric Range
State
NH              308.0
AL              220.0
MN              220.0
BC              220.0
IN              210.0

In [11]:
df.groupby('State')[['City', 'Make', 'Model']].value_counts()

State  City            Make        Model
AK     Fairbanks       FORD        FUSION     1
AL     Smiths Station  TESLA       MODEL 3    1
AR     Little Rock     NISSAN      LEAF       1
                       TESLA       MODEL 3    1
                                   MODEL Y    1
                                             ..
WA     Zillah          TESLA       MODEL S    1
                       VOLKSWAGEN  ID.4       1
WI     South Range     TESLA       MODEL Y    1
WY     Cheyenne        TESLA       MODEL 3    1
       Sheridan        BMW         IX         1
Name: count, Length: 10274, dtype: int64

In [14]:
df_WA = df.loc[df['State'] == 'WA']
df_WA.sort_values(by='City', ascending=True)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
32963,JN1AZ0CP1B,Grays Harbor,Aberdeen,WA,98520.0,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73,0,19.0,244336767,POINT (-123.81619 46.97606),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...,5.302700e+10
104494,5YJ3E1EB4M,Grays Harbor,Aberdeen,WA,98520.0,2021,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,19.0,140039224,POINT (-123.81619 46.97606),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...,5.302700e+10
41043,1G1RC6S53J,Grays Harbor,Aberdeen,WA,98520.0,2018,CHEVROLET,VOLT,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,53,0,19.0,476889472,POINT (-123.81619 46.97606),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...,5.302700e+10
114742,5YJYGDEE8M,Grays Harbor,Aberdeen,WA,98520.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,19.0,148529216,POINT (-123.81619 46.97606),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...,5.302700e+10
35517,1G1FY6S03M,Grays Harbor,Aberdeen,WA,98520.0,2021,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,19.0,156530545,POINT (-123.81619 46.97606),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...,5.302700e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57684,5YJ3E1EB7P,Yakima,Zillah,WA,98953.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,15.0,226094739,POINT (-120.26186 46.40186),PACIFICORP,5.307700e+10
90668,1C4JJXP66M,Yakima,Zillah,WA,98953.0,2021,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,15.0,213616364,POINT (-120.26186 46.40186),PACIFICORP,5.307700e+10
42452,5YJXCDE23J,Yakima,Zillah,WA,98932.0,2018,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238,0,15.0,170230959,POINT (-120.18721 46.33937),PACIFICORP,5.307700e+10
101,JN1AZ0CP0C,Yakima,Zillah,WA,98953.0,2012,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73,0,15.0,185917665,POINT (-120.26186 46.40186),PACIFICORP,5.307700e+10
35908,WBY1Z4C52F,Yakima,Zillah,WA,98953.0,2015,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,72,0,15.0,281550811,POINT (-120.26186 46.40186),PACIFICORP,5.307700e+10

In [30]:
crosstab_city_model = pd.crosstab(df_WA['City'], df_WA['Make'])
crosstab_city_model.loc['Total'] = crosstab_city_model.sum()

def total_cars_for_city(row):
    return row.sum()

crosstab_city_model['Total_cars_for_city'] = crosstab_city_model.apply(total_cars_for_city, axis=1)

crosstab_city_model

Make,AUDI,AZURE DYNAMICS,BENTLEY,BMW,CADILLAC,CHEVROLET,CHRYSLER,FIAT,FISKER,FORD,...,RIVIAN,SMART,SUBARU,TESLA,TH!NK,TOYOTA,VOLKSWAGEN,VOLVO,WHEEGO ELECTRIC CARS,Total_cars_for_city
City,,,,,,,,,,,,,,,,,,,,,
Aberdeen,1,0,0,3,0,14,1,3,0,11,...,1,0,0,32,0,9,3,1,0,112
Acme,0,0,0,0,0,1,0,0,0,3,...,0,0,0,2,0,0,0,0,0,6
Addy,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,3
Airway Heights,0,0,0,0,0,2,1,0,0,2,...,0,0,0,5,0,1,0,1,0,16
Alderdale,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yakima,10,0,1,16,2,60,2,4,0,25,...,3,2,1,198,0,32,8,5,0,455
Yarrow Point,6,0,0,11,0,3,1,0,0,2,...,2,0,0,80,0,0,1,3,0,126
Yelm,1,0,0,4,0,18,7,4,0,17,...,4,0,0,72,0,9,3,6,0,189
Zillah,0,0,0,3,0,0,0,0,0,3,...,1,0,0,6,0,0,1,2,0,23
Total,2479,7,3,5563,111,10819,1894,809,14,6655,...,1428,274,184,56980,3,4645,3362,2510,3,124419

In [40]:
crosstab_make_model = pd.crosstab(df_WA['Make'], df_WA['Model'])
crosstab_make_model.loc['Total'] = crosstab_make_model.sum()
crosstab_make_model['Total_auto_for_make'] = crosstab_make_model.sum(axis=1)

crosstab_make_model

Model,330E,500,530E,740E,745E,745LE,918,A3,A7,A8 E,...,V60,VOLT,WHEEGO,WRANGLER,X3,X5,XC40,XC60,XC90,Total_auto_for_make
Make,,,,,,,,,,,,,,,,,,,,,
AUDI,0,0,0,0,0,0,0,569,10,3,...,0,0,0,0,0,0,0,0,0,2479
AZURE DYNAMICS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
BENTLEY,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
BMW,388,0,366,26,9,2,0,0,0,0,...,0,0,0,0,290,1851,0,0,0,5563
CADILLAC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,111
CHEVROLET,0,0,0,0,0,0,0,0,0,0,...,0,4875,0,0,0,0,0,0,0,10819
CHRYSLER,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1894
FIAT,0,809,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,809
FISKER,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,14
FORD,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6655
GENESIS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,44
HONDA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,798
HYUNDAI,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1998
JAGUAR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,219
JEEP,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1670,0,0,0,0,0,1930
KIA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4836
LAND ROVER,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,36
LEXUS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,54
LINCOLN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,199
LUCID MOTORS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,118
MERCEDES-BENZ,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,651
MINI,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,711
MITSUBISHI,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,618
NISSAN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12932
POLESTAR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,634
PORSCHE,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,898
RIVIAN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1428
SMART,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,274
SUBARU,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,184
TESLA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,56980
TH!NK,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
TOYOTA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4645
VOLKSWAGEN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3362
VOLVO,0,0,0,0,0,0,0,0,0,0,...,10,0,0,0,0,0,497,654,824,2329
WHEEGO ELECTRIC CARS,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,3
Total,388,809,366,26,9,2,1,569,10,3,...,10,4875,3,1670,290,1851,497,654,824,124238